name: Build

on:
  push:
  pull_request:

jobs:
  build-cp:
    name: Build ClassPad app
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/therainbowphoenix/gint-docker:main

    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git ca-certificates

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Azur
        run: bash scripts/setup-azur.sh

      - name: Build
        run: fxsdk build-cp

      - name: Upload HH3
        uses: actions/upload-artifact@v4
        with:
          name: AzurTemplate
          path: "**/AzurTemplate.hh3"
          if-no-files-found: error
